name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...
      
    - name: Run Worker
      run: go run worker/main.go
      
    - name: Run Starter
      run: go run start/main.go

#    - name: Test
#      run: go test -v ./...
